language: python
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

python:
  - "3.6"

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev # provides unbuffer utility
      - swig
      - python3-pykcs11

stages:
  - test

jobs:
  include:
    - stage: test
      env:
        - TESTS=1 ODOO_REPO="odoo/odoo" MAKEPOT="1"
    - stage: test
      env:
        - TESTS=1 ODOO_REPO="OCA/OCB"
env:
  global:
    - VERSION="14.0" TESTS="0" LINT_CHECK="0" MAKEPOT="1"

install:
  - git clone --depth=1 https://github.com/akretion/maintainer-quality-tools.git
    ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - pip install PyPDF2==1.26.0

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
