version: 0.2

env:
    variables:
        VERSION: "12.0"
        TESTS: "1"
        LINT_CHECK: "1"
        TRANSIFEX: "0"
        ODOO_REPO: "open-synergy/odoo"
phases:
    install:
        runtime-versions:
            python: 3.7
        commands:
            - echo ${CODEBUILD_SRC_DIR}
            - ls ${CODEBUILD_SRC_DIR}
            - export TRAVIS_BUILD_DIR=${CODEBUILD_SRC_DIR}
            - echo ${TRAVIS_BUILD_DIR}
            - apt-get update
            - apt-get -y upgrade
            - apt-get -y install expect-dev python-lxml python-simplejson python-serial python-yaml postgresql-client postgresql
#             - curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
            - apt-get install -y nodejs
            - pip install coveralls
            - pip install codecov
            - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
            - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
            - travis_install_nightly
    build:
        commands:
            - travis_run_tests
    post_build:
        commands:
            - travis_after_tests_success
